### ISSUE TITLE
Fahrer → Auto und Mitfahr → Mitfahrer*in

### ISSUE THREAD

**Issue by nrchtct** [uclab-potsdam/klimataz#351] opened 2022-10-06 09:16 UTC
The description below does not match the car driver/passenger wording…  I would suggest this change:

Mitfahrer → Auto (Mitfahrer\*in)
Fahrer → Auto (Fahrer\*in)

![klimaland_taz-7](https://user-images.githubusercontent.com/578924/194275089-5b5cf51e-0676-4d00-a3dd-5f15d94da0f1.png)

**Comment by johannahaha** [comment] 2022-10-06 12:26
duplicate of #310

**Closed by johannahaha** 2022-10-06 12:26 UTC
Labels: duplicate
